     <?php $contact = $this->contact?>
      <form action="<?php $this->link('contact', 'save')?>" method="post" id="form" accept-charset="utf-8">
            <h1><?php echo $contact->getName()?></h1>
            <div class="buttons">
            	<button type="submit" class="js-submit">Kaydet</button>
            	<button type="button" class="cancel" onclick="parent.location='<?php $this->link('contact', 'delete', $contact->getId())?>'">Sil</button>
            	<button type="button" class="cancel" onclick="parent.location='<?php $this->link('contact', 'index')?>'">Geri Dön</button>
            </div>
            
            <div class="clear"></div>
            <hr />

                <section id="contact">
                    <section class="left">
                        <div class="general">
                            <input type="hidden" name="id" value="<?php echo $contact->getId()?>" />
							<h3>Ad ve Soyad:</h3>
                            <p>
                                <input type="text" name="name" value="<?php echo $contact->getName()?>"/>
                            </p>
                        </div><!--general-->
                        <div class="emails">
                            <h3>E-Posta:</h3>
							<div class="email">
                                    <p>
                                        <input type="text" name="email" value="<?php echo $contact->getEmail()?>" />
                                    </p>
                             </div>
                        </div><!--emails-->
                        <div class="phonenumbers">
                            <h3>Telefon Numarası:</h3>
                            <p>
                            	<input type="text" name="phonenumber" value="<?php echo $contact->getPhoneNumber()?>" />
                            </p>
                        </div><!--phonenumbers-->
                        <div class="addresses">
                            <h3>Posta Adresi:</h3>
							<p>
                            	<textarea name="address" rows="5" cols="20"><?php echo $contact->getPostalAddress()?></textarea>
                            </p>
                        </div><!--addresses-->
                        <div class="organisations">
                            <h3>Organizasyon:</h3>

                            <div class="organisation">
                                <p>
                                    <label for="company">Şirket:</label>
                                    <input type="text" name="company" value="<?php echo $contact->getCorporation()?>" />
                                </p>
                                <p>
                                    <label for="title">Ünvan:</label>
                                    <input type="text" name="title" value="<?php echo $contact->getJobTitle()?>" />
                                </p>
                            </div><!--organisation-->
                        </div><!--organisations-->
                    </section><!--left-->
                    <section class="right">
                        <p> <label for="note">Not: </label></p>
                        <p><textarea name="note" rows="50" cols="30"><?php echo $contact->getNote()?></textarea></p>
                    </section><!--right-->

                    <div class="clear"></div>
                </section><!--contact-->

                   <script type="text/javascript" src="theme.js"></script>
                   <script type="text/javascript">
                        (function()
                    {
                                                    $('.js-submit').on('click', function(e)
                        {
                            e.preventDefault();
                            $.post('<?php $this->link('contact', 'save')?>', $('#form').serialize(), function(data)
                        {
                            if(data.result == 'success')
                                {
                                    $('#result').attr('class','success').text('Kaydedildi!').slideToggle(500).delay(2000).fadeToggle(500);
                                }
                            else
                                {
                                    $('#result').attr('class','error').text('Kaydedilemedi').slideToggle(500).delay(2000).fadeToggle(500);
                                }
                        });

                        });
                    })();

                    </script>
                    <div id="result"></div>
                    </form>