            <h1>Kişiler</h1>
            <div class="buttons">
            	<button type="submit" onclick="parent.location='<?php $this->link('contact', 'new')?>'">Yeni Kayıt</button>
            	<button type="button" class="cancel" onclick="parent.location='<?php $this->link('contact', 'index')?>'">Tüm Liste</button>
            </div>
            <div class="clear"></div>
            <hr />
            <table>
                <tr>
                    <th>Adı ve Soyadı</th>
                    <th>E-Posta</th>
                    <th>Telefon</th>
                    <th>Ünvan/Organizasyon</th>
                </tr>
                <?php foreach($this->contacts as $contact):?>
                <tr>
                    <td><a href="<?php $this->link('contact', 'view', $contact->getId())?>">
                  	  <?php echo $contact->getName()?></a></td>
                    <td><?php echo $contact->getEmail()?></td>
                    <td><?php echo $contact->getPhoneNumber()?></td>
                    <td><?php echo $contact->getJobTitle()?>(<?php echo $contact->getCorporation()?>)</td>
                </tr>
                <?php endforeach;?>

            </table>
                <div id="searchform">
                    <form action="<?php $this->link('contact','search')?>" method="post" accept-charset="utf-8">
                         <input type="text" name="s" /><button type="submit">Ara</button>
                    </form>
                </div>