<div id="loginform">
<h1>Üye Girişi</h1>
	<?php if($this->contains('message')):?>
	<h3><?php echo $this->message?></h3>
	<?php endif;?>
	<form action="<?php $this->link('user', 'login')?>" method="post" accept-charset="utf-8">
	<p>
		<label for="username">Kullanıcı Adı: </label>
		<input type="text" name="username" />
	</p>
	<p>
		<label for="password">Parola: </label>
		<input type="password" name="password" />
	</p>
	<p>
		<button type="submit">Giriş Yap</button> <button type="button" onclick="parent.location='<?php $this->link('user', 'registerform')?>'">Kayıt Ol</button>
	</p>
	</form>
	
</div>