<?php $this->doctype()?>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=<?php $this->charset()?>" />
	<title><?php $this->title()?></title>
	
	<meta name="description" content="<?php $this->description()?>" />
	<meta name="author" content="Ömer ÖZKAN" />
	<meta name="generator" content="OzkanMVC" />
	<link href="<?php $this->defaultCss()?>" rel="stylesheet" type="text/css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
</head>
<section id="container">